version: '3.8'

services:
  task_postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_task_db_password
      POSTGRES_DB: task_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  app:
    build: .
    depends_on:
      - task_postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://task_postgres:5433/task_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root_task_db_password
    ports:
      - "8080:8080"


volumes:
  postgres-data: