version: '3.8'

services:
  task_postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_task_db_password
      POSTGRES_DB: task_db
    ports:
      - "5433:5432"
    volumes:
      - task-postgres-data:/var/lib/postgresql/data
  user_postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_user_db_password
      POSTGRES_DB: user_db
    ports:
      - "5434:5432"
    volumes:
      - user-postgres-data:/var/lib/postgresql/data


volumes:
  task-postgres-data:
  user-postgres-data: