spring.datasource.url=jdbc:postgresql://localhost:5433/task_db
spring.datasource.username=postgres
spring.datasource.password=root_task_db_password
spring.datasource.driver-class-name=org.postgresql.Driver


server.port=8080
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop